name: 'Lint Python Code' # La pipeline tiene que tener un nombre
on: # Cu치ndo se va a activar
  push: # Only execute pipeline when someone pushes a commit to these branches
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint: # Name of the job
    runs-on: ubuntu-latest
    steps: # Cada gui칩n es un step
      - uses: actions/checkout@v4 # @v_numero es la versi칩n
      - uses: actions/setup-python@v5
        # with es como un par치metro del step
        with: 
          python-version: "3.13"
      - name: Install dependencies
        run: |
          uv add ruff
      - name: Lint the project
        run: ruff check --output-format=github